baseURL = "https://www.teilzeithippies.de"
languageCode = "de-de"
title = "TeilzeitHippies"

[blackfriday]
   hrefTargetBlank = true

[[menu.main]]
    name = "Essen"
    identifier = "essen"
    url = "/essen/"
    weight = 100

[[menu.main]]
    name = "Bewegung"
    identifier = "bewegung"
    url = "/bewegung/"
    weight = 110

[[menu.main]]
    name = "Natur"
    identifier = "natur"
    url = "/natur/"
    weight = 120


[[menu.main]]
    name = "Selbst"
    identifier = "selbst"
    url = "/selbst/"
    weight = 130


[[menu.main]]
    name = "Vertrauen"
    identifier = "vertrauen"
    url = "/vertrauen/"
    weight = 140